### ISSUE TITLE
Documentation suggestion: Could the "landing pages" for the major sections keep their ToCs more visible?

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1040]
Taking https://textual.textualize.io/styles/ into account, if you land on that page and your browser window isn't very wide, or if you're in a mobile view, it can seem like the page is empty:

<img width="1324" alt="Screenshot 2022-10-27 at 21 44 15" src="https://user-images.githubusercontent.com/28237/198394238-d19861cd-8884-45cf-9ef6-1faf3d2aa731.png">

While the ToC is of course off to the left in the three-bars menu, and there is prev/next navigation at the bottom of the page, the main impression does seem to be that of a "to be done" page (I found it especially tricky to find things on mobile). Making the window just a bit wider does reveal the ToC, of course:

<img width="1332" alt="Screenshot 2022-10-27 at 21 44 23" src="https://user-images.githubusercontent.com/28237/198394505-53eae647-5320-4634-ae09-b423cbbc24e6.png">

I wonder if it might be possible to stop the ToC disappearing so readily, or perhaps having it in the main body of the page?

**Comment by willmcgugan** [comment]
Yes, I'm not keen on that behaviour either. I'd prefer that the TOC is shown at the top of the page, rather than hidden in a hamburger menu. 

@squidfunk Is there a relevant setting for this?

**Comment by squidfunk** [comment]
The TOC is on the left (all anchors of the current page). What you're talking about is the navigation sidebar. The sidebar is hidden on widths below `1220px`. Over the years, this turned out to be the optimal value to segment notebooks from tablets. If you wish to move that value further down, i.e., to keep the navigation sidebar, you have to recompile the theme and change some variables. Search the code base for `1220px` to learn what you need to replace.

Unfortunately it's impossible to make this configurable via `mkdocs.yml`.

**Comment by willmcgugan** [comment]
Yeah, it is the sidebar. But I don't think this is necessarily a breakpoint tweak. It's probably related to the type of content we want to display.

let me illustrate... Here's a shot with the navigation sidebar visible:

<img width="1434" alt="Screenshot 2022-10-30 at 11 59 40" src="https://user-images.githubusercontent.com/554369/198877278-1066ad0c-1a15-4029-99a3-8c91af5456a2.png">

This page is a reference, so you want to jump around rather than read is sequentially. The index doesn't have much content, because you're expected to click the Style you want via the sidebar.

Here's what it looks like with a smaller window / phone / tablet:

<img width="867" alt="Screenshot 2022-10-30 at 11 59 46" src="https://user-images.githubusercontent.com/554369/198877370-b559be5f-9d23-4d72-b269-cfde5319bed7.png">

With the sidebar hidden by default, it's not clear how to navigate this page. I honestly would not think to look in the hamburger menu, and I've seen others struggle with that.

I think the current behaviour makes sense for more linear docs, but not for references. I guess what I'd like is for the index page to contain the links in the sidebar, rather than the hamburger menu.

I guess we could compile the index pages ourselves, but it seems like something mkdocs could do for us?

**Comment by squidfunk** [comment]
I'm not sure what we should do here. On smaller screens, the sidebar needs to be collapsed into the hamburger menu – there's just not enough space to render both. The hamburger icon is learned behavior and has been used for 10 years now. Please note that we always have to strike a balance with Material for MkDocs. Empty documentation pages are nothing we can optimize for. I suggest adding some links to the index page, e.g. using [card grids](https://squidfunk.github.io/mkdocs-material/reference/grids/).
