### ISSUE TITLE
Loading a large file with Static

### ISSUE THREAD

**Issue by 7hacker** [Textualize/textual#1322]
In the example below a file of 512KB is loaded as part of a Static Widget. It works but takes several seconds, atleast > 20s to load up. Maybe this is not efficient and there is a better way to load the task, if this is not an actual Issue?
```
class Content(Static):
    """Content widget."""

    def compose(self) -> ComposeResult:
        fp = open("large_file.log", "r")
        yield Static(fp.read())
```

**Comment by rodrigogiraoserrao** [comment]
Hey there, thanks for reaching out.
I have tried running your example with a 512KB file I created locally and while I can definitely notice the time it takes to create the widget, the time it takes to do so is still under a second... So, this begs these questions:
 - where is the file you are trying to access? Is it a local file, or are you accessing it through, say, FTP?
 - how big/complex is the application you are creating this widget in?
 - what terminal app and OS are you running this under?
 - are you running this on old hardware?

Try running the tiny app that I show here ↓ and see how long it takes. Is it still >20s?

```py
from textual.app import App, ComposeResult
from textual.widgets import Static

class MyWidget(Static):
    def compose(self) -> ComposeResult:
        with open("large_file.log", "r") as f:
            contents = f.read()
        yield Static(contents)

class MyApp(App[None]):
    def compose(self) -> ComposeResult:
        yield MyWidget()

MyApp().run()
```

These questions are just to help troubleshoot the issue you are experiencing.

Regardless of the cause of this slowdown, we can make one suggestion: when loading up data or when performing some time-consuming operation, do that asynchronously so that the TUI can remain responsive while the data is being loaded, or while some computations are being performed, etc.

Here is an example:

```py
import asyncio

from textual.app import App, ComposeResult
from textual.events import Key
from textual.widgets import Label

async def load_huge_data() -> str:
    await asyncio.sleep(3)
    return "This is the data."

class MyApp(App[None]):
    def compose(self) -> ComposeResult:
        yield Label("Loading...")
        asyncio.create_task(self.populate_label_with_data())

    async def populate_label_with_data(self) -> None:
        data = await load_huge_data()
        self.query_one(Label).update(data)

    def on_key(self, event: Key) -> None:
        if event.key == "r":
            self.screen.styles.background = "red"
        else:
            self.screen.styles.background = "black"

MyApp().run()
```

The function `load_huge_data` is a function that takes 3 seconds to load some data (could be 30 seconds, 3 minutes, or 3 days). When we compose the app, we yield a label that just says that we are loading data and then we tell `asyncio` to start working on populating the label by calling `populate_label_with_data`.
_While_ we work on loading the data, we can press the key `R` to change the background colour to red or any other key to change it to black. This shows that the app is still responsive, even while we do some work to fetch the data.
When we get the data, we update the label to show it.

**Comment by willmcgugan** [comment]
Reading from a file is a blocking operation. Putting it in a task would not help I’m afraid, as it would still suspend asyncio while reading. Fortunately there is the aiofiles lib which enables asynchronous file access.

To address the issue of the slow populating of the widget, it’s likely because the widget does wrapping and various other things up front (a guess, haven’t profiled). You might find the TextLog widget to be a more efficient log viewer, since it does more work “on demand”.
