### ISSUE TITLE
Document CSS units

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1344]
We need to document Textual CSS units (%, vw, fr etc).

Where do we put them? I have a feeling this should go in the guide in a section under CSS, but also in the Reference section with more detail.

**Comment by WMRamadan** [comment]
@willmcgugan @rodrigogiraoserrao can this be labeled as `good first issue` there seems to be no issues with that label

**Comment by davep** [comment]
This is currently being worked on by @rodrigogiraoserrao.

**Comment by WMRamadan** [comment]
@davep Oh OK, are there any issues in the backlog that can be labeled as `good first issue`?

**Comment by davep** [comment]
[There doesn't appear to be](https://github.com/Textualize/textual/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22+no%3Aassignee). Perhaps, rather than ping folk involved and tracking this issue, it might make more sense to ask about something that general in [the discussions](https://github.com/Textualize/textual/discussions) or on the [Discord Server](https://discord.gg/Enf6Z3qhVr).

**Comment by WMRamadan** [comment]
Great, thanks didn't know about the Discord Server.

**Comment by rodrigogiraoserrao** [comment]
Sorry for not replying during the weekend, @WMRamadan.
To be honest, this wouldn't even be a great first issue because there are some docs layout decisions to be made here, etc. But thanks for your enthusiasm!

In any case, following @davep's suggestions seems the way to go.

**Comment by rodrigogiraoserrao** [comment]
Tracking the status of CSS units documentation (this comment may get updated):

Created a folder under "Reference / Styles" that contains pages for the different units:

 - color
 - fractional
 - integer
 - percentage
 - scalar

The basic syntax of each was also extracted to a small snippet that can be cut into the multiple rules that make use of each unit, so that we only need to maintain a single file and the changes to each unit are reflected everywhere else.
