### ISSUE TITLE
Widgets styled with a `:hover` can sometimes end up with their styles sticking

### ISSUE THREAD

**Issue by davep** [Textualize/textual#1372]
It's not 100% clear to me yet exactly what happens, but this can be seen with 5x5 from our examples, where a `:hover` style can get stuck after the mouse has left the widget. See here for example:

![Screenshot 2022-12-15 at 16 05 58](https://user-images.githubusercontent.com/28237/207911142-8122dfca-41d5-45fd-a97d-64965e691963.png)

In the image 3 cells have the hover style (the background slightly lighter than the background for the other "off" cells). One of them, at the time of the screenshot, had the mouse over it, the other 2 didn't.

This *seems* to happen if you're a bit quick with mouse movements.

Needs some investigation and a proper route to reproduction found.

**Comment by davep** [comment]
After a wee bit more playing, it looks like the issue mainly crops up if the mouse cursor passes out of the terminal window pretty quickly (suggesting that the removal of `:hover` relies on seeing that some other widget now has the mouse over it, but the mouse isn't over anything?).

**Comment by rodrigogiraoserrao** [comment]
The real issue was in the fact that we were trying to start a second animation (back to the default background color) while the first animation hasn't started yet, so we skip the creation of the new animation but the old one still runs to completion.

This issue also affects animations that start with a delay. If we set an animation A -> B with a delay of 10s and 1s later we set an animation B -> A, then the animation A -> B will run after 9s but the animation B -> A will not run because it was not created in the first place.
