### ISSUE TITLE
[DataTable] Implement update_cell method

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1483]
We need a method to update the contents of a cell after it has been added.

```python
def update_cell(self, row_index:int, cell:CellType):
```

**Comment by darrenburns** [comment]
Some notes:

When we update a cell at a coordinate, we need a way to invalidate all of the cell cache items which correspond to that coordinate.

Right now, the cell cache items are keyed by `(row_index, column_index, style, cursor, hover)` - and so we cannot quickly look up the items for a given coordinate.

We could wrap the cell LRUCache and create a new data structure which automatically tracks all of the coordinate → LRUCache key mappings, so that for a given coordinate, we can quickly jump to all of the cache items and invalidate them.

### Note

- I haven’t considered updates required to the other caches quite yet and whether they need to be invalidated or not. I suspect they will.
- A lot of the caching we have in place falls apart as soon as we add any insertion or sorting functionality. We’d probably need to update our caching to use the “keys” rather than coordinates like we discussed the other day.
