### ISSUE TITLE
TextLog viewable area incorrect if surrounded by margin

### ISSUE THREAD

**Issue by ofek** [Textualize/textual#1579]
The final lines are unviewable equal to the margin amount:

```python
class Configure(Screen):
    DEFAULT_CSS = """
    TextLog {
        margin: 1;
        height: 1fr;
    }
    """

    def compose(self):
        yield TextLog()

    def on_key(self, event):
        text_log = self.query_one(TextLog)
        text_log.write('\n'.join(map(str, range(100))))
```

![dc](https://user-images.githubusercontent.com/9677399/212739059-46050126-370b-4266-a090-5de68adaef8c.PNG)

**Comment by davep** [comment]
Looking at this more carefully, and checking with others, this is working as intended. `margin` is something that happens in addition to the size of the widget -- so in this case it's pushing your `TextLog` down. To illustrate, here's a more extreme version with a border to helps how what's going on (note that the margin will be *outside* the border of the widget):

```python
from textual.app      import App, ComposeResult
from textual.widgets  import Header, Footer, TextLog
from textual.binding  import Binding
from textual.reactive import reactive

class TextLogAndMargin( App[ None ] ):

    CSS = """
    TextLog {
        border: round red;
        margin: 10;
        height: 1fr;
    }
    """

    BINDINGS = [
        Binding( "l", "log", "Log" ),
    ]

    log_line = reactive( 0 )

    def compose( self ) -> ComposeResult:
        yield Header()
        yield TextLog()
        yield Footer()

    def action_log( self ) -> None:
        for _ in range( 50 ):
            self.query_one( TextLog ).write( f"This is log line {self.log_line}" )
            self.log_line += 1

if __name__ == "__main__":
    TextLogAndMargin().run()
```

resulting in this:

<img width="922" alt="Screenshot 2023-01-17 at 10 11 30" src="https://user-images.githubusercontent.com/28237/212870833-b812e4c2-6134-4c54-bf79-d40cffe6f9a3.png">

In other words the widget will be sized to 1 whole fraction of the container and will then have its margin applied.

There's a couple of different ways of getting what you seem to be after here. One would be to use `padding` rather than margin. Again, taking an extreme case:

```python
from textual.app      import App, ComposeResult
from textual.widgets  import Header, Footer, TextLog
from textual.binding  import Binding
from textual.reactive import reactive

class TextLogAndMargin( App[ None ] ):

    CSS = """
    TextLog {
        border: round red;
        padding: 10;
        height: 1fr;
    }
    """

    BINDINGS = [
        Binding( "l", "log", "Log" ),
    ]

    log_line = reactive( 0 )

    def compose( self ) -> ComposeResult:
        yield Header()
        yield TextLog()
        yield Footer()

    def action_log( self ) -> None:
        for _ in range( 50 ):
            self.query_one( TextLog ).write( f"This is log line {self.log_line}" )
            self.log_line += 1

if __name__ == "__main__":
    TextLogAndMargin().run()
```

resulting in this:

<img width="922" alt="Screenshot 2023-01-17 at 10 11 49" src="https://user-images.githubusercontent.com/28237/212870891-ee01b184-8e56-4bbe-8116-1454345ef271.png">

Another approach would be to size it to `100%`; in this case the height will be calculated *inclusive* of the margin. For example:

```python
from textual.app      import App, ComposeResult
from textual.widgets  import Header, Footer, TextLog
from textual.binding  import Binding
from textual.reactive import reactive

class TextLogAndMargin( App[ None ] ):

    CSS = """
    TextLog {
        border: round red;
        margin: 10;
        height: 100%;
    }
    """

    BINDINGS = [
        Binding( "l", "log", "Log" ),
    ]

    log_line = reactive( 0 )

    def compose( self ) -> ComposeResult:
        yield Header()
        yield TextLog()
        yield Footer()

    def action_log( self ) -> None:
        for _ in range( 50 ):
            self.query_one( TextLog ).write( f"This is log line {self.log_line}" )
            self.log_line += 1

if __name__ == "__main__":
    TextLogAndMargin().run()
```

<img width="922" alt="Screenshot 2023-01-17 at 10 13 42" src="https://user-images.githubusercontent.com/28237/212871230-9c2ce2bd-2c28-4a85-a2cb-06977bf8d9ed.png">

**Comment by ofek** [comment]
Here is a reduced version of my current screen, you will notice that you can't see the bottom of the text log:

```python
from textual.app import App, ComposeResult
from textual.containers import Container, Horizontal
from textual.widget import Widget
from textual.widgets import Button, Footer, Header, Input, Label, TextLog


class LabeledInput(Horizontal):
    DEFAULT_CSS = """
    LabeledInput {
        height: 3;
    }

    LabeledInput Label {
        margin-top: 1;
        width: 1fr;
        text-align: right;
    }

    LabeledInput Input {
        width: 5fr;
    }
    """


class ConfigurationInput(Widget):
    DEFAULT_CSS = """
    ConfigurationInput Button {
        margin: 1;
        width: 100%;
    }

    ConfigurationInput TextLog {
        margin: 1;
        height: 100%;
    }
    """

    def compose(self) -> ComposeResult:
        yield LabeledInput(Label('Repo name:'), Input())
        yield LabeledInput(Label('Repo path:'), Input())
        yield LabeledInput(Label('GitHub user:'), Input())
        yield LabeledInput(Label('GitHub token:'), Input(password=True))
        yield LabeledInput(Label('Jira email:'), Input())
        yield LabeledInput(Label('Jira token:'), Input(password=True))
        yield Button('Save', variant='primary', disabled=True)
        yield TextLog()


class Configure(App):
    CSS = """
    #screen-configure {
        layout: grid;
        grid-size: 2;  /* two columns */
        grid-columns: 1fr;
        grid-rows: 1fr;
    }

    #screen-configure-input {
        height: 100%;
    }

    #screen-configure-logo {
        height: 100%;
    }
    """

    def compose(self) -> ComposeResult:
        yield Header()
        yield Container(
            Container(ConfigurationInput(), id='screen-configure-input'),
            Container(Label('placeholder'), id='screen-configure-logo'),
            id='screen-configure',
        )
        yield Footer()

    def on_input_changed(self, event: Input.Changed) -> None:
        text_log = self.query_one(TextLog)
        text_log.write('\n'.join(map(str, range(100))))


if __name__ == "__main__":
    Configure().run()
```

**Comment by ofek** [comment]
Changing the height of the text box to `1fr` hides less lines but still a few are

**Comment by davep** [comment]
> Changing the height of the text box to `1fr` hides less lines but still a few are

That would be correct. The thing to remember with %ages is that they're in relation to that dimension of the container. So if you say you want the `TextLog` to be `height: 100%`, you're saying "I want it to be the height of the container". On the other hand setting it to `1fr` says "I want it to be as high as I can possible fit in". The former will cause it to go off the bottom (which is what some folk want, along with scrolling, etc), the latter will make it fit "just so".

The last few remaining lines are solved by [what I mention above](https://github.com/Textualize/textual/issues/1579#issuecomment-1385152174): the use of `margin` is pushing the `TextLog` ever so slightly off the bottom of the screen. As you'll see, once you're in that state, you're 2 lines off. Those two lines come from the use of `margin` on the `Button` and the `TextLog`. If you swap `margin` to `padding` you'll find that it it will fit fine.

**Comment by ofek** [comment]
I'll close this, for now I'm doing:

```css
ConfigurationInput TextLog {
    margin: 1;
    padding-bottom: 2;
    height: 1fr;
}
```

**Comment by willmcgugan** [comment]
@ofek Here's a slight modification to your code, which I think shows what is happening:

There are a few additional CSS lines in `ConfigurationInput` which add a border and enables scrolling.

Your `TextLog` is being clipped because it doesn't fit in to its container. The TextLog is 100% of height (of `ConfigurationInput`) but you also have labels and buttons which adds to this height. When you set a dimension to `100%`, it is 100% of its container, not 100% of remaining space.

For layouts that should fit within a given space, we recommend fixed units plus `fr` units for flexible sizes.

```python
from textual.app import App, ComposeResult
from textual.containers import Container, Horizontal
from textual.widget import Widget
from textual.widgets import Button, Footer, Header, Input, Label, TextLog


class LabeledInput(Horizontal):
    DEFAULT_CSS = """
    LabeledInput {
        height: 3;
    }

    LabeledInput Label {
        margin-top: 1;
        width: 1fr;
        text-align: right;
    }

    LabeledInput Input {
        width: 5fr;
    }
    """


class ConfigurationInput(Widget):
    DEFAULT_CSS = """
    ConfigurationInput {
        border: solid red;
        overflow: auto;
    }
    ConfigurationInput Button {
        margin: 1;
        width: 100%;
    }

    ConfigurationInput TextLog {
        margin: 1;
        height: 100%;
    }
    """

    def compose(self) -> ComposeResult:
        yield LabeledInput(Label("Repo name:"), Input())
        yield LabeledInput(Label("Repo path:"), Input())
        yield LabeledInput(Label("GitHub user:"), Input())
        yield LabeledInput(Label("GitHub token:"), Input(password=True))
        yield LabeledInput(Label("Jira email:"), Input())
        yield LabeledInput(Label("Jira token:"), Input(password=True))
        yield Button("Save", variant="primary", disabled=True)
        yield TextLog()


class Configure(App):
    CSS = """
    #screen-configure {
        layout: grid;
        grid-size: 2;  /* two columns */
        grid-columns: 1fr;
        grid-rows: 1fr;
    }

    #screen-configure-input {
        height: 100%;
    }

    #screen-configure-logo {
        height: 100%;
    }
    """

    def compose(self) -> ComposeResult:
        yield Header()
        yield Container(
            Container(ConfigurationInput(), id="screen-configure-input"),
            Container(Label("placeholder"), id="screen-configure-logo"),
            id="screen-configure",
        )
        yield Footer()

    def on_input_changed(self, event: Input.Changed) -> None:
        text_log = self.query_one(TextLog)
        text_log.write("\n".join(map(str, range(100))))


if __name__ == "__main__":
    Configure().run()
```

**Comment by ofek** [comment]
Oh nice thank you that overflow attribute enabled scrolling so I can actually see the bottom, that will be very useful to know in the future if I encounter clipping again and no scrollbar appears

**Comment by davep** [comment]
> I'll close this, for now I'm doing:
> 
> 
> 
> ```css
> 
> ConfigurationInput TextLog {
> 
>     margin: 1;
> 
>     padding-bottom: 2;
> 
>     height: 1fr;
> 
> }
> 
> ```

As mentioned earlier: the use of margin is what's causing the issue. To be testing what I proposed you'd be using padding, not margin.

**Comment by ofek** [comment]
on my screen at least the margin as I had it in addition to the new padding to account for both defined margins shows the last line of the text log. is that the same on your end?

**Comment by davep** [comment]
Perhaps I wasn't clear, apologies. I was saying to use padding *instead of* margin. As in:

```diff
--- ofek_orig.py	2023-01-18 08:42:14
+++ ofek_mod.py	2023-01-18 08:45:06
@@ -25,13 +25,13 @@
 class ConfigurationInput(Widget):
     DEFAULT_CSS = """
     ConfigurationInput Button {
-        margin: 1;
+        padding: 1;
         width: 100%;
     }

     ConfigurationInput TextLog {
-        margin: 1;
-        height: 100%;
+        padding: 1;
+        height: 1fr;
     }
     """
```

Giving this:

<img width="1562" alt="Screenshot 2023-01-18 at 08 45 49" src="https://user-images.githubusercontent.com/28237/213125256-be4e242d-f8f6-4922-8686-a0096f1f4c28.png">

Of course, that does throw off a couple of other things (see the button for example), but I wanted to illustrate the importance of the difference between using margin and padding. [The description of the box model in the docs](https://textual.textualize.io/guide/styles/#box-model) may also be useful here.

The upshot of this being, for the purposes of this issue anyway, `TextLog` is fine here, as is `margin`; I just wanted to be as clear as possible that the "clipping" you're seeing is expected given the styles chosen.
