### ISSUE TITLE
Containers always left-align the items

### ISSUE THREAD

**Issue by anzhi0708** [Textualize/textual#1677]
As mentioned in [this discussion](https://github.com/Textualize/textual/discussions/1643), CSS code like this

```python
from textual.app        import App, ComposeResult
from textual.containers import Vertical
from textual.widgets    import Header, Footer, Button, Label, Input

class CenterApp( App[ None ] ):

    CSS = """
    Vertical {
        border: round red;
        align: center middle;
    }

    Label {
        border: round yellow;
    }

    Input {
        width: 50%;
    }
    """

    def compose( self ) -> ComposeResult:
        yield Header()
        yield Vertical(
            Label( "This is a label" ),
            Button( "This is a button, it's longer" ),
            Input( placeholder="This is an input, it's even longer still" )
        )
        yield Footer()

if __name__ == "__main__":
    CenterApp().run()
```

does not work as expected. 

![image](https://user-images.githubusercontent.com/57821133/214901726-75620416-94b4-443b-b2e5-251ddeb35f1e.png)

Not sure if this issue is duplicated; if so, pls close this issue as duplicated :-P

**Comment by willmcgugan** [comment]
This is the expected behaviour.

We did think about changing it, but on reflection the current behaviour is desirable. The `align` property applies to children, but it shouldn't change the position of children relative to each other.

We may add some kind of "inline-align" property to allow individual aligning of children, but in the meantime adding a Horizontal container is a fine solution.

**Comment by davep** [comment]
(while reviewing older issues) See also #950. Closing both as expected behaviour (and possibly an extra way of doing this in the future).
