### ISSUE TITLE
post_message optimization

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1739]
When a message is posted via `post_message` or `post_message_no_wait` it is placed on a queue.

The widget may not have a handler for the message, but it still has to go through the queue. If it bubbles, it will do the same thing on the parent.

This means that many messages go in and out of queues, without resulting in any work. 

We can optimize by checking in `post_message` if there is a potential handler for that messages. If there isn't then the message should bubble or be discarded as normal. This could reduce a significant amount of work.

**Comment by rodrigogiraoserrao** [comment]
Won't this result in duplication of code? Because the code that handles messages in the queue already checks for a handler and calls it and then makes the message bubble if the handler isn't there, right? (Assuming the message is supposed to bubble.)

Or are you going to do the checking + bubbling earlier and assume messages in the queue already have the handler?

**Comment by willmcgugan** [comment]
@darrenburns It might, yeah. I wonder if I can refine that to "discard early if nothing in this widget and parents process the message". I suspect many would satisfy that.

@rodrigogiraoserrao It would, but checking for the handler is relatively inexpensive. It's more expensive to post things on queues and dispatch them in another task. So I'm assuming it will be a win overall.

**Comment by willmcgugan** [comment]
On reflection, we wouldn't be able to detect required work done in on_message and on_event. So this feels like a non starter. Closing.
