### ISSUE TITLE
CSS class manipulation Widget methods clash with classes initialisation

### ISSUE THREAD

**Issue by rodrigogiraoserrao** [Textualize/textual#1744]
When you create an instance of a widget you can pass in CSS classes as a string with the classes separated by spaces (which I find odd in Python).
E.g., `Button(classes="class-a class-b something-else yet-another")`.

Then, the methods `add_class`, `remove_class`, and `toggle_class`, all expect a variable number of arguments corresponding to the classes.
E.g., `button.add_class("class-a", "class-b", "something-else", "yet-another")`.

In my opinion, this is suboptimal.

Suggested changes that seem reasonable:

 - change the `xxx_class` methods to accept classes in the same format as when instantiating widgets;
 - change the type of the parameter `classes` to be an iterable of strings representing classes, one per string.

**Comment by willmcgugan** [comment]
The `classes` in the constructor is taken from the HTML attribute `class`, renamed because `class` is a Python keyword. Which explains its origins as a single string. 

I get how a container would feel more natural from a Python POV, i.e. `classes=['foo', 'bar']`. But the most typical use case is a single class, and devs will do `classes='bar'` and get confusing results. You could argue that they are just doing it wrong, and they should get the results they asked for, and not the results they wanted. But that is contrary to the ethos of going an extra mile for the devs.

Typing doesn't save us  here. If we type it as an iterable of strs, then MyPy won't warn us `classes="foo"` is a mistake -- because a str is also an iterable of str. We could explicitly require a list, but then it feels contrary to duck-typing. Why insist on a list when from the devs POV a tuple or set should work.

Maybe we could do something at runtime that checks if it is a str, and adds the single class. But then what if the dev really wanted to add classes `b` `a` and `r`, and they are annoyed that `classes="bar"` doesn't do that.

Ultimately it makes it easier to write compose methods with the `classes` as a str. It is almost always going to be written as a literal, so there is no need to pass it as a reference. 

And its easier to type. Compare `Button(classes=["foo", "bar", "baz"])` to `Button(classes="foo bar baz")` 

These arguments don't hold up everywhere. I wouldn't advocate replacing lists of strs with space separated tokens elsewhere in the code. But I think the status quo works better in context.

**Comment by rodrigogiraoserrao** [comment]
Alright, that makes sense! But I interpreted it as a strong argument against changing the way the `classes=` in the constructor works.

How about changing `add_class("one", "two", "three")` to `add_class("one two three")` so that it matches the constructor parameter?

**Comment by rodrigogiraoserrao** [comment]
Or `add_classes("one two three")`?

**Comment by willmcgugan** [comment]
I would say no. At that level, you do want a little more strictness. The positional arguments don't suffer from the issue above.

It's the same in JS, IIRC.
