### ISSUE TITLE
Disabled widgets should still scroll

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#1912]
It appears as though disabled containers makes the scrollbars also disabled, and consequently scrolling is disabled.

I think disabled widgets should still scroll as normal. Possibly make the Scrollbar widget un-disableable?

**Comment by willmcgugan** [comment]
@davep maybe one for you?

**Comment by davep** [comment]
Yup, that sounds like an unintended consequence. 😁

**Comment by davep** [comment]
*[After checking locally]* Okay, I think I misread that first; I read that as "a widget that is disabled can't be scrolled by a parent that is scrolling and isn't disabled" (which would be an unintended consequence). To be clear, this is that a widget that itself is scrollable (say a long Markdown viewer, a data table, text log, etc...) can't be scrolled because, in having disabled it, it can't be focused and so the scrollbars don't work any more (which is, or at least was, an intended consequence).

Things for us to ponder here:

- Does it makes sense that a widget that has been disabled (and so can't receive focus) can still be interacted with, for a subset of interaction?
- If we were to allow scrollbar interaction in this case, how would that work given that the widget can't receive focus?
- If we were to make it so that a pointing device *can* interact with the widget, despite it being disabled (and so unable to receive focus), this will then cause an unfortunate dichotomy between keyboard input and pointing device input; simply put a mouse/trackpad/trackball/touchscreen user would be able to scroll but a pure-keyboard user wouldn't be able to.
- How have other UI frameworks done this over the years? (I've not gone looking yet but in my mind's eye as I write this I seem to picture fully-disabled-no-scroll widgets rather than kinda-disabled-but-kinda-allowing-non-focused-input-at-least-when-scrolling widgets).

**Comment by willmcgugan** [comment]
Closing.  Not sure there is any need for this after all.
