### ISSUE TITLE
Sort method in`DataTable` doesn't support `rich.Text` types

### ISSUE THREAD

**Issue by msempere** [Textualize/textual#2261]
Coming from https://github.com/Textualize/textual/pull/2243.

The `sort` method in`DataTable` doesn't support `rich.Text` types stored in the cells. When that is done a `TypeError: '<' not supported between instances of 'Text' and 'Text'` error is thrown because `rich.Text` have no [rich comparison operators](https://docs.python.org/2.7/reference/datamodel.html#object.__lt__) defined.

cc @rodrigogiraoserrao

**Comment by rodrigogiraoserrao** [comment]
My original thought (from the PR linked above):

 > “Maybe we could add a key parameter to the sort methods, akin to how sorted(..., key=...) works.”

@darrenburns might be better suited to determine if this makes sense.

**Comment by msempere** [comment]
> A `key` method makes sense. But I have no issue adding comparison methods to `Text` which just treat it like a string.

@willmcgugan adding them to `Text` is probably the best idea. I'll work on that.
Could you assign that issue to me? thanks!

**Comment by candidtim** [comment]
Only having the ordering functions on the `rich.Text` won't be enough for all use cases (although I entirely support this change too). For example: I want to sort a column with humanized numbers (e.g., file sizes like "42 Bytes" and "2 MiB"). It needs to be sorted based on the raw values themselves, independently of their representation. 

Adding a `sort_fn` to the `add_column` method would not be helpful in **this** case either, because it implies that it should be possible to convert the textual representation back into whatever can be ordered. But otherwise I think it is a nice flexible solution too.

One solution to the above problem is to allow setting the values and their representation separately (and maybe use the `str(value)` as a default representation). Then, either use the values directly, or also allow a custom function to extract the sort keys, based on the values.

Meanwhile, for a workaround I extend the `rich.text.Text` to implement the ordering. For example:

```python
@functools.total_ordering
class Sortable(Text):
    """Like rich.text.Text, but with ordering based on a raw value"""

    def __init__(self, value, *args, **kwargs):
        self.value = value
        super().__init__(*args, **kwargs)

    def __lt__(self, other: "Sortable") -> bool:
        return self.value < other.value

    def __eq__(self, other: "Sortable") -> bool:
        return self.value == other.value
```

and later use it like so:

```python

    def watch_xyz(self, ...):
        ...
        self.table.add_row(Sortable(file_size, naturalsize(file_size), ...)

```

It allows customizing the ordering logic in any way necessary by changing the `__lt__` implementation. For example I did things like sticky top/bottom rows, etc.

**Comment by TomJGooding** [comment]
> Adding a `sort_fn` to the `add_column` method would not be helpful in **this** particular case either, because it implies that it is possible to convert the textual representation back into whatever can be ordered, which in practice is not always the case.

I'm assuming you've looked at #3090, could you give an example where this would not work?

**Comment by candidtim** [comment]
> I'm assuming you've looked at #3090, could you give an example where this would not work?

As far as I understand the example from above still holds, but please let me know if I am missing something. If I understand the change well, the new `key` argument accepts a function which will be called with a row content (key and cell values). This means that if I want to sort based on some value, this value necessarily needs to be present in the row cells in one way or another. What if the value I want to sort on is not directly present in the row? For example, I would show humanized numbers ("1 MiB", "1 GiB") in the column, but would want to sort it based on actual numbers (1 MiB < 1 GiB). Since the actual number is not present in the row, how would the `key` function obtain it?

**Comment by sharkusk** [comment]
In the sort routine you can always un-humanize the numbers.  You might get some round-off errors if you don't have enough precision in your human readable numbers, but in general works pretty well.  (I do this in my app today with a DataTable and a custom sort() function.)

**Comment by rodrigogiraoserrao** [comment]
> How would the `key` function obtain it?

The `key` function can do whatever you want with the values it receives, namely “un-humanize” them.
See, for example, the parameter `key` in the built-in `sorted`: https://github.com/Textualize/textual/pull/3289

**Comment by guystreeter** [comment]
I would very much like to supply my own callback to the `sort` function. Simply handing me the row key would be enough, but having all the row data would be better.
An alternative would be enabling a hidden column. I could put a sortable value there that doesn't get displayed.

**Comment by TomJGooding** [comment]
I stumbled across this open issue looking for something else. You can now sort your DataTable with a custom function (or other callable) in Textual v0.41.0 - see https://textual.textualize.io/widgets/data_table/#sorting
