### ISSUE TITLE
`Switch` should stop the `Click` event from bubbling

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2366]
At the moment `Switch` handles `Click` but then lets it bubble; there's no good reason to do that and it also stops the ability to write something like this:

```python
from textual.app        import App, ComposeResult
from textual.containers import Horizontal
from textual.widgets    import Header, Footer, Label, Switch

class LabeledSwitch( Horizontal ):

    def on_click( self ) -> None:
        self.query_one(Switch).toggle()

class ClickableLabelApp( App[ None ] ):

    def compose( self ) -> ComposeResult:
        yield Header()
        with LabeledSwitch():
            yield Label( "Click me!" )
            yield Switch()
        yield Footer()

if __name__ == "__main__":
    ClickableLabelApp().run()
```

where the idea is to make a compound widget that lets you click on the `Label` or the `Switch` and the `Switch` will toggle -- only it doesn't work if you click on the `Switch` because it ends up double-toggling.

**Comment by rodrigogiraoserrao** [comment]
(This issue is reserved for the [EuroPython 2023 sprint](https://ep2023.europython.eu/sprints). If you are not participating in the sprint, please refrain from working on this issue. Thanks!)

@davep 's explanation of what we want to achieve is pretty clear, provided [you know what bubbling means](https://textual.textualize.io/guide/events/#bubbling).
This should be a simple fix.
You can even use Dave's example app, above, in your tests for your fix.

Good luck and have fun!

**Comment by seifertm** [comment]
I'd like to have a go at this.
