### ISSUE TITLE
Implement MultiSelect

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2518]
We need a widget to select multiple options from a list.

Similar to HTML Select with multiple, but greater usability.

I think this should be built on OptionList, but have a checkbox by each item. The return value should be a tuple of values.

I don't think we need a overlay (like Select). Since this is designed to show multiple things, it probably should be multiple lines long, scrolling as required.

**Comment by Alphix** [comment]
I have a widget like that...but it's based on RadioSet rather than OptionList (and uses a bunch of CheckBoxes instead of RadioButtons...)

Do you want me to submit at PR?

The widget looks something like this:
![image](https://github.com/Textualize/textual/assets/4029895/34140641-9fcc-48a8-8fd2-42d8ce8cab71)

**Comment by Alphix** [comment]
@willmcgugan : sure, it's in PR #2524

**Comment by davep** [comment]
(In anticipation of the PR coming in tomorrow, and so I don't forget...) See also #2379.
