### ISSUE TITLE
Docking and scrolling interaction bug?

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#2525]
Run the sample app below and tab through the checkboxes repeatedly until you get to the bottom. The focused checkbox will be hidden behind the footer.

In fact, viewing the final checkbox at all appears to be impossible. It's obscured by the docked footer and cannot be scrolled into view.

My understanding is that the space docked widgets consume should be reserved, such that the content behind it can be scrolled into view.

```python
from textual.app import App, ComposeResult
from textual.widgets import Checkbox, Footer


class ScrollOffByOne(App):
    def compose(self) -> ComposeResult:
        for number in range(1, 100):
            yield Checkbox(str(number))
        yield Footer()


app = ScrollOffByOne()
if __name__ == '__main__':
    app.run()

```

**Comment by willmcgugan** [comment]
On reflection this is the desired behaviour.

The very nature of `dock` is that it floats over things. Ultimately it is the parent which defines the scrollable area. If the Footer and checkboxes share the same parent then the footer will float over the docked area. 

Look what happens if I style the footer to have a larger height and a margin:

```python
from textual.app import App, ComposeResult
from textual.widgets import Checkbox, Footer


class ScrollOffByOne(App):
    CSS = """
    Footer {
        margin: 2 4;
        height: 4;
    }

    """

    def compose(self) -> ComposeResult:
        for number in range(1, 100):
            yield Checkbox(str(number))
        yield Footer()


app = ScrollOffByOne()
if __name__ == "__main__":
    app.run()

```

If floats above the checkboxes and you can see the last checkbox.

<img width="1282" alt="Screenshot 2023-05-09 at 17 27 16" src="https://github.com/Textualize/textual/assets/554369/af58df52-b019-4f24-8151-921e5a7522ac">

It does look like a bug, and is a bit of a gotcha, but the solution is to put the Checkboxes in their own scrollable container.

@darrenburns What do you think?

**Comment by darrenburns** [comment]
The explanation makes sense, but in our layout docs (in the guide) do we not have an example (the one with the blue sidebar) showing that docking "pushes" sibling content away?

**Comment by willmcgugan** [comment]
It still does that. Here's the footer docked at the top:

<img width="1282" alt="Screenshot 2023-05-09 at 18 32 14" src="https://github.com/Textualize/textual/assets/554369/babf2b96-1538-4938-a1a0-6353e0a51e18">

But with a vertical layout, things will always be added to the bottom, which may force them under a docked widget.

**Comment by willmcgugan** [comment]
On reflection. It doesn't have to work this way.
