### ISSUE TITLE
Setting theme doesn't work a second time

### ISSUE THREAD

**Issue by ankraft** [Textualize/textual#2583]
This is a rather strange one. I have a textual app that may be run multiple times from a parent app (all in the same Python runtime), but not in parallel.
What I am doing is to instantiate a new App instance every time and run() it. Now, when I set the theme mode (`self.dark = False`) in the `__init()__` method, from the second instantiation on the theme doesn't change. However, if I assign to `self.dark` in the `compose()` method everything works fine.

The example code:

```python
from textual.app import App, ComposeResult
from textual.widgets import Static, Footer

class TestApp(App):

    BINDINGS = [
        ("q", "quit", "Quit"),
    ]

    def __init__(self) -> None:
        super().__init__()
        self.dark = False   # This doesn't work the second time
    
    def compose(self) -> ComposeResult:
        # self.dark = False     # This works fine
        yield Static('Hello, world!')
        yield Footer()

    def action_quit(self) -> None:
        self.exit()

if __name__ == "__main__":

    # First run
    app = TestApp()
    app.run()

    # Second run
    app = TestApp()
    app.run()

```

**Comment by TomJGooding** [comment]
`App.dark` is a **class attribute** set outside of `init` and shared by all instances.  I confess I can't explain _exactly_ what is happening here, but essentially the issue is that you have a conflict with two attributes with the same name. It looks like you've already found that setting the theme outside of `init` works as expected?

```python
class Test:
    dark = True

    def __init__(self) -> None:
        self.dark = False


test = Test()
print(test.dark)  # False
print(Test.dark)  # True
```

**Comment by willmcgugan** [comment]
`dark` is actually a descriptor, so it should behave like an instance attribute.

Generally I'd recommend setting reactives in a message handler. If you set dark to False in `on_mount` everything works as expected.

That said, I don't have an explanation for the behaviour in the issue. Does look like something is being associated with the class rather than the instance.

**Comment by ankraft** [comment]
@TomJGooding , @willmcgugan  Thanks for the explanations.
Even if it is a class attribute it is not clear (at least to me) why the behaviour is different between the first and the second instances. I moved the `dark` setting to `compose()`, and this works fine, though I am not happy to do the assignment there.

**Comment by TomJGooding** [comment]
Sorry ankraft if I've mislead you - Will seems to have put me straight and already opened a PR for this.

**Comment by ankraft** [comment]
@TomJGooding No problem. Thanks for taking the time. And it's great to see a PR so quickly!
