### ISSUE TITLE
`Markdown` widget: Code blocks in lists are incorrectly ordered, sometimes don't appear

### ISSUE THREAD

**Issue by jamescooke** [Textualize/textual#2676]
## Current behaviour

Very similar to this old issue in Rich: https://github.com/Textualize/rich/issues/1036

When we use the same content (a list with a code block):

```sh
cat > order.md
```

```md
This is a test.

1. first item
2. second item

       code block

Normal text
```

And then render it with Frogmouth:

```sh
frogmouth order.md
```

Then the code block does not appear:

![Screenshot from 2023-05-28 16-34-15](https://github.com/Textualize/frogmouth/assets/781059/8f664ba9-2607-47b8-8c3f-1940da95d03b)

If we tweak the code block to use triple backticks, then the block appears, but out of order:

```sh
cat > order2.md
```

```md
This is a test.

1. first item
2. second item

   ``
   code block
   ``

Normal text
```

> Please forgive my use of a double backtick above - I wasn't able to get a triple backtick to render in a code block in this markdown issue body 😬 . I've attached the file for confirmation: [order2.md](https://github.com/Textualize/frogmouth/files/11584996/order2.md)

```sh
frogmouth order2.md
```

![Screenshot from 2023-05-28 16-36-40](https://github.com/Textualize/frogmouth/assets/781059/969241ca-d0ce-40d6-902a-e350b9e3c286)

## Expected behaviour

Render code block as part of the second item consistently.

Rich appears to render both markdown excerpts OK (and they appear the same). Tested with `rich==13.3.5`
![Screenshot from 2023-05-28 18-50-20](https://github.com/Textualize/frogmouth/assets/781059/b616c5e4-e964-4412-9abd-f0785ec4982b)

**Comment by davep** [comment]
Given `Markdown` is based on `markdown-it`, the first thing to do here is be sure how it handles things. Looks like it renders this as expected:

![Screenshot 2023-05-28 at 20 55 32](https://github.com/Textualize/textual/assets/28237/cca94d19-260a-4fd5-beb7-26d8dc895805)

As such, at first glance, this would appear to be a bug in `Markdown`.

**Comment by jamescooke** [comment]
Thanks for moving the issue from Frogmouth @davep 

I've confirmed the behaviour is in the Textual `Markdown` widget as follows:

* Used the `markdown.py` example file [from the docs](https://textual.textualize.io/widgets/markdown/#__tabbed_1_2)
* Replaced `EXAMPLE_MARKDOWN` variable with the failing contents from `order.md` and `order2.md` in turn.
* Ran each example with `python markdown.py` with `textual==0.26.0` installed.
* Received the same render as Frogmouth (with code block not appearing with `order.md` and out of order in `order2.md`) as screenshotted in the original issue description.

**Comment by TomJGooding** [comment]
I'm sure that @davep is already way ahead of me on this, but posting anyway just in case it helps!

I experimented with a blockquote inside a list item and it looks like Textual renders this as expected:

![image](https://github.com/Textualize/textual/assets/101601846/66cc49dd-0798-486f-af46-c40d875b735a)

I'm still trying to get to grips with the [Markdown update method](https://github.com/Textualize/textual/blob/main/src/textual/widgets/_markdown.py#L647-L792), but it looks like a blockquote token type is appended to the `stack`, whereas a code block is one of few token types (fence) that is instead appended to the `ouput`.

I _hoped_ it might be as simple as changing this to the stack, but this breaks the docs `markdown_viewer.py` example.

**Comment by davep** [comment]
Half of the above will be fixed by #2803 (the part above indented code blocks).

I'm about to take a look at the problem of the code block appearing out of order when part of a list. The general problem can be seen here:

<img width="724" alt="Screenshot 2023-06-19 at 14 16 56" src="https://github.com/Textualize/textual/assets/28237/620fe393-4973-40d0-8609-d56e1678d7aa">

I've not dived into the code yet, but I wanted to get an overview of what the widget tree looks like. Right off it seems clear that a list is an "atomic" or "leaf" widget, rendering its content and not containing other widgets (in other words the items in the list *aren't* widgets). Meanwhile the code is a `MarkdownFence` so can't be inline in the list.

This fits perfectly with what @TomJGooding finds above.

**Comment by davep** [comment]
Actually, scratch that, I'm talking nonsense (for a change). Turns out that I was managing to render the `tree` just a little too soon after doing the `update` on the `Markdown`. (╯°□°）╯︵ ┻━┻ 

So, after I wait a moment and *then* refresh things the tree makes a lot more sense:

<img width="724" alt="Screenshot 2023-06-19 at 14 54 58" src="https://github.com/Textualize/textual/assets/28237/9dd9dc6c-7e16-4225-98a6-bb0664515772">

**Comment by davep** [comment]
@TomJGooding You hoped right, like 99% of the way there right anyway:

> I hoped it might be as simple as changing this to the stack, but this breaks the docs markdown_viewer.py example.

Came down to https://github.com/Textualize/textual/pull/2803/commits/e2dd7114765f21e20faf1b63e920d9267c28031e

**Comment by TomJGooding** [comment]
Ah, that makes sense. I don't think that co-author was really deserved, but thank you!

**Comment by davep** [comment]
> I don't think that co-author was really deserved, but thank you!

You found the right spot and mostly found the fix, I just copied your homework and tweaked it. ;-)
