### ISSUE TITLE
Allow widgets to limit types

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#2749]
We have a Tooltip class which is derived from Static, which means it inherits CSS from `Widget` and `Static`.

This is as expected, but Tooltip is unusual in that it is inserted in to the DOM automatically. The dev may not expect to see Tooltip in a query, and could end up styling it if they are foolish enough to write CSS targeting Widgets or Static.

I think the solution may be to allow widgets to opt out of inheriting their base class CSS. So that `Tooltip` is the only type name it responds to.

This will fix https://github.com/Textualize/textual/issues/2723

**Comment by davep** [comment]
After coming up with #2753 and looking at the code some more to come up with good tests and the like, I noticed `inherit_css` exists and seems to already do what this needs, albeit via a slightly different route. So, with this test code:

```python
"""https://github.com/Textualize/textual/pull/2753"""

from textual.app        import App, ComposeResult, RenderResult
from textual.containers import Horizontal, Vertical
from textual.widgets    import Static, TextLog

class CustomParent( Static ):

    def __init__( self ) -> None:
        super().__init__()
        self.border_title = self.__class__.__name__

    def render(self) -> RenderResult:
        return str( self._css_type_names )

class CustomChild( CustomParent ):
    pass

class CustomGrandChild( CustomChild, inherit_css=False ):
    pass

class CSSTypeExplorerApp( App[ None ] ):

    CSS = """
    Static, TextLog {
        border: panel green;
        padding: 1;
    }

    CustomGrandChild {
        border: panel red;
    }
    """

    def compose( self ) -> ComposeResult:
        with Horizontal():
            with Vertical():
                yield CustomParent()
                yield CustomChild()
                yield CustomGrandChild()
            with Vertical():
                yield TextLog( id="statics" )
                yield TextLog( id="query-one" )

    def on_mount( self ) -> None:
        self.query_one( "#statics", TextLog ).border_title = "Statics in the DOM"
        for static in self.query( Static ):
            self.query_one( "#statics", TextLog ).write( f"{static!r}" )
        self.query_one( "#query-one", TextLog ).border_title = "query_one( 'CustomChild' )"
        self.query_one( "#query-one", TextLog ).write( f"{self.query_one( CustomChild )!r}" )

if __name__ == "__main__":
    CSSTypeExplorerApp().run()
```

(note `inherit_css=False` on `CustomGrandChild`) I get the desired (by this issue) outcome:

![Screenshot 2023-06-08 at 13 45 55](https://github.com/Textualize/textual/assets/28237/e6045f5e-01e0-406b-ac28-2241421fa5f7)

So, either I'm totally misunderstanding things or we've had this all along. ¯\\_(ツ)_/¯ 

I suspect #2723 can be fixed by just making `Widget` `inherit_css=False` and having it provide all of its own styles (I'd imagine it doesn't inherit much of anything from whatever parent it uses).

**Comment by willmcgugan** [comment]
So `inherit_css=False` means that CustomGrandChild won't be styles / queried by its base classes?

If that's the case, then lets add that to Tooltip!

**Comment by davep** [comment]
Yup. Looks like we collectively forgot we already had this feature. 🤦🏻‍♀️

I'll close all of this and go update Tooltip instead.
