### ISSUE TITLE
Add a method to `DirectoryTree` that allows for reloading an individual node

### ISSUE THREAD

**Issue by davep** [Textualize/textual#2757]
The question cropped up on Discord and seems like a useful thing to have: the ability to say "clear out and reload this specific node" when using `DirectoryTree` -- a developer may know that a specific directory has been modified and they want to refresh the content.

**Comment by rodrigogiraoserrao** [comment]
(This issue is reserved for the [EuroPython 2023 sprint](https://ep2023.europython.eu/sprints). If you are not participating in the sprint, please refrain from working on this issue. Thanks!)

The [`DirectoryTree` widget](https://textual.textualize.io/widgets/directory_tree/) loads its directory upon instantiation and only once, so it displays static data.

The widget should grow a method called something like`reload_node` and that method should do what @davep describes above.
It should clear whatever is under that node and it should load it again.

Good luck and have fun!

**Comment by gergely-elias** [comment]
I'd like to work on this one. Thanks!
