### ISSUE TITLE
Can't change a Select widget promt and options

### ISSUE THREAD

**Issue by ShinoNia** [Textualize/textual#2983]
```
yield Select(options = [("Opt 1", 1), ("Opt 2", 2)], id='select', allow_blank=False, prompt="select")
select_widget = self.query_one('#select')
```

These lines don't have effect:
```
select_widget._options = [("Opt 3", 1)]
select_widget.options = [("Opt 3", 1)]
select_widget.prompt = "select 2"
```

For the options, I can use `select_widget.set_options([("Opt 3", 1)])`, but I can't change the prompt and it's quite inconvenient

**Comment by davep** [comment]
@ShinoNia Your report is a little unclear, so I want to check a couple of things. You say that this doesn't work:

```python
select_widget._options = [("Opt 3", 1)]
```

You're attempting to access an internal value there (denoted by the leading `_`); no public interface of Textual will have a heading `_` so that wouldn't be the way to do it.

You also say this doesn't work:

```python
select_widget.options = [("Opt 3", 1)]
```

which is correct. That isn't the documented method of updating the options for a `Select`.

As you appear to have discovered, [`set_options`](https://textual.textualize.io/widgets/select/#textual.widgets._select.Select.set_options) is the documented method for setting new options on a `Select`.

Can I just be clear here that you're not reporting anything to do with this?

Assuming you're not, would I be correct in understanding that the issue you're reporting here is that this:

```python
select_widget.prompt = "select 2"
```

has no visible effect? If so I agree and that would appear to be a bug that requires addressing.

**Comment by rodrigogiraoserrao** [comment]
@davep related to #2603.

**Comment by davep** [comment]
@rodrigogiraoserrao Not if I'm reading it correctly. `Select.prompt` is more akin to `Input.placeholder`.
