### ISSUE TITLE
Command palette flicker when there are no results

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3278]
When there are no results, each keypress produces a flicker where the "No matches found" message is shown and hidden. I think we should be able to avoid this, so the "No matches found" message persists.

https://github.com/Textualize/textual/assets/554369/98e93373-e7e1-4f95-84e7-0f193684cc7c

**Comment by davep** [comment]
Thanks; I'll double check this. I *think* it used to work like this and then I made a point of ensuring the message got cleared up each time until it was established because, with a slow command source, as you backspaced it could end up looking like no matches were found when that hadn't actually been established yet. Consider typing:

`this is a really long command for which there is no match`

and then hitting backspace once, and unknown to the user, there *will* be a match but it'll take seconds to load it up: it'll say there isn't a match and so they might start backspacing up more and causing the search to start again when it wasn't necessary.

**Comment by davep** [comment]
Suggestion from @willmcgugan over the desks: keep it sort of as is, but rather than show it the moment we know there are no matches, set a timer to show it, and kill that timer when more typing happens (akin to how we made the loading indicator works).

I like this approach.
