### ISSUE TITLE
Command Palette visual tweaks

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3279]
Can we rename "Search..."  to "Command Palette Search". To provide some additional context to the user.

I think it may look a little better if there is no padding around the input. May be wrong, but worth comparing.

The top and bottom borders use $accent, which may be a little too intense. We generally want $accent to be reserved for things like highlights, but the borders are no so important. Suggest $primary instead.

**Comment by davep** [comment]
> I think it may look a little better if there is no padding around the input. May be wrong, but worth comparing.

If/when making such a change, leep in mind that the command palette optionally has a "go" button, for when the developer has elected to set `CommandPalette.run_on_select` to `False`, because they wish the user to be able to confirm their command first.

![Screenshot 2023-09-13 at 08 37 32](https://github.com/Textualize/textual/assets/28237/af94cec2-97f6-4185-bb1a-ab65f4c07fef)

![Screenshot 2023-09-13 at 08 37 37](https://github.com/Textualize/textual/assets/28237/912ea960-949a-40d3-9c1d-5551c6371e59)
