### ISSUE TITLE
The Command Palette matches spaces

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3281]
I suspect this is the highlighting, and not the matching per se. But if your search contains spaces, it highlights those.

I think we should exclude those from the match.

<img width="772" alt="Screenshot 2023-09-11 at 17 01 53" src="https://github.com/Textualize/textual/assets/554369/1b287c73-767a-450c-80b7-8533ea6332f9">

**Comment by davep** [comment]
To be pedantic for a moment (but I think it's important to the issue): it's not really the case that the command palette matches spaces -- the command palette doesn't do matching, it just sends out requests for matches and gathers up the results. The matching of, and highlighting of, spaces, is down the the command sources; they can decide how best to do this and how the highlighting is done.

In the case of the builtin system command source it's using Textual's fuzzy matcher. I think it's a reasonable thing to change, but I just wanted to highlight that it's that code that would need the change, and that other command sources could use their own matching and highlighting strategy.

**Comment by davep** [comment]
Another thing to consider/clarify, is how it's expected to affect this sort of situation. Currently the Textual fuzzy matcher, when asked to look for `ark mode`, would make a hit with score 1:

![Screenshot 2023-09-14 at 08 26 19](https://github.com/Textualize/textual/assets/28237/bac5c7e4-8e2d-44c9-9642-9f13785aeadf)

If, for example, all spaces were ignored for the purposes of matching, the same search would end up scoring lower beause then it would be matching two different groups, rather than one:

![Screenshot 2023-09-14 at 08 26 47](https://github.com/Textualize/textual/assets/28237/b7fd925f-0680-4bbc-bd38-a1aa599acc51)

```python
>>> Matcher("ark mode").match("this is dark mode")
1.0
>>> Matcher("ark mode", ignore_whitespace=True).match("this is dark mode")
0.9411764705882353
```
