### ISSUE TITLE
Update dependancies to support Python 3.12

### ISSUE THREAD

**Issue by davidbrochart** [Textualize/textual#3491]
With Python 3.12:
```console
pip install textual
```
Fails with:
```
ERROR: Could not find a version that satisfies the requirement tree_sitter_languages>=1.7.0; python_version >= "3.8" and python_version < "4.0" (from textual) (from versions: none)
ERROR: No matching distribution found for tree_sitter_languages>=1.7.0; python_version >= "3.8" and python_version < "4.0"
```

**Comment by davidbrochart** [comment]
I opened https://github.com/grantjenks/py-tree-sitter-languages/issues/30.

**Comment by willmcgugan** [comment]
We're going to split out the tree sitter stuff next release. So at least you get a plain looking textarea if you can't install tree sitter. Fingers cross they release for 3.12 soon.

**Comment by GabDug** [comment]
I opened pull requests on [py-tree-sitter](https://github.com/tree-sitter/py-tree-sitter/pull/161) and [py-tree-sitter-languages](https://github.com/grantjenks/py-tree-sitter-languages/pull/27), hope it can be merged soon :)

**Comment by chrisphilipov** [comment]
> I opened pull requests on [py-tree-sitter](https://github.com/tree-sitter/py-tree-sitter/pull/161) and [py-tree-sitter-languages](https://github.com/grantjenks/py-tree-sitter-languages/pull/27), hope it can be merged soon :)

Is the second PR correct? As I can see this PR being more relevant [py-tree-sitter-languages](https://github.com/grantjenks/py-tree-sitter-languages/pull/28) vs the linked PR which is about aarch64 support raised from another user. Probably just a classic "off by one error" as the PRs are /27 and /28 but figured I'd raise :D

**Comment by willmcgugan** [comment]
I think we may have everything we need to support 3.12 now.

**Comment by rodrigogiraoserrao** [comment]
I'm going to go ahead and tackle this.
I expect this to take 1h to update the deps and then have a go at a clean installation on a Mac machine and on a Windows machine.
If something doesn't work, the time estimate will expand to a couple of hours for sure.

**Comment by rodrigogiraoserrao** [comment]
Since we've split the syntax highlighting dependencies into an extra `textual[syntax]`, textual can be installed on 3.12 successfully.

We're still waiting on `tree-sitter-languages` to merge the PR mentioned by GabDug/chrisphilipov to enable building wheels for `tree-sitter-languages` on 3.12.

Thus, the only thing left here is updating our CI to test on 3.12.
However, testing on 3.12 will “break” CI even if we skip the tests related to syntax highlighting because syrupy will see unused snapshot tests and report a test run failure. (See https://github.com/tophat/syrupy/issues/842.)
In order to work around this, we introduce a pytest marker `syntax` that we add to the tests that depend on syntax highlighting and then break up the GH Action testing workflow into two:

 - the general one installs all dependencies and runs all tests on all Python versions except 3.12; and
 - another set of steps doesn't install the syntax highlighting dependencies and it will use the `syntax` marker to deselect some tests.
