### ISSUE TITLE
Move cursor after adding rows

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3544]
Reported on Discord. If you add rows then call move cursor, the view won't follow the cursor.

A workaround is to use `call_after_refresh`, which suggests something on idle needs to be done before `move_cursor` works?

```python
from textual.app import App
from textual.widgets import DataTable


class TestMove(App):
    def compose(self):
        yield DataTable()

    def on_mount(self):
        dt = self.query_one(DataTable)
        dt.add_column("thecolumn")

        for row in range(1000):
            dt.add_row(f"row number {row}")

        dt.move_cursor(row=500, column=1, animate=True)
        # self.call_after_refresh(dt.move_cursor, row=500, column=1, animate=False)


TestMove().run()
```

**Comment by TomJGooding** [comment]
I think similar to #3533, the problem is that DataTable dimensions are only calculated on idle. The window in `scroll_to_region` has  a height/width of zero, so the scrolling with `move_cursor` won't work.

But I'm sure you figured that out already, I'm just not sure of the proper fix.

**Comment by darrenburns** [comment]
Yeah, exactly right. The `virtual_size` needs to be updated before `move_cursor` works. Since the `virtual_size` is recomputed inside `on_idle`, if you try to move the cursor immediately, it won't work.

I think the fix is literally just to use `call_after_refresh(self._scroll_cursor_into_view)` inside `move_cursor`, since this can only work after `on_idle` runs.

I've implemented this fix in https://github.com/Textualize/textual/pull/3552

**Comment by TomJGooding** [comment]
Both fixes a lot more straightforward then I expected!
