### ISSUE TITLE
CSS errors have a broken path

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#3569]
CSS errors will create an invalid path to the CSS, if the CSS is in code. This is because it adds the widget name to the path.

Here's an example:

![Image](https://github.com/Textualize/textual/assets/554369/a24d2eae-c16e-4757-8c21-abeecde746c8)

If you click the heading it should take you to the file containing the error, but it doesn't because the path is invalid.

It would be nice to display the widget within the title, but it should probably be a separate field.

**Comment by rodrigogiraoserrao** [comment]
Much like the `:line:col` is displayed but it doesn't break the file link, I can just fix the file link and leave the `:object:line:col` in the displayed link.

Another alternative is to tweak `Token` so that it keeps track of where it comes from (which Widget + class variable) and separate it from the link.

**Comment by rodrigogiraoserrao** [comment]
My preference would be for the panel title to be something like:

```
Error at /Users/willmcgugan/projects/textual/src/textual/widget.py:2:9 in Widget.DEFAULT_CSS
```

**Comment by willmcgugan** [comment]
Works for me.

Bonus points if you can figure out how to point to the line in the Python file, rather than relative to the CSS. But don't spend too much time on that.
