### ISSUE TITLE
`$boost` in `textual colors` not matching what's in the docs

### ISSUE THREAD

**Issue by davep** [Textualize/textual#3649]
Raised by someone on Discord, if you look at the `$boost` selection in `textual colors`:

![Screenshot 2023-11-08 at 08 48 04](https://github.com/Textualize/textual/assets/28237/1e986ed2-a8fc-4985-a634-7347f775a128)

it doesn't seem to match what you see in the docs:

![Screenshot 2023-11-08 at 08 48 34](https://github.com/Textualize/textual/assets/28237/ca88532c-c433-4952-9bda-92836100d9cd)

This is on macOS, tested with various terminals (at least kitty, wez, iTerm, contour).

Noting it here as something to look into later (or for someone else to grab and check).

**Comment by TomJGooding** [comment]
Checking the screen recording of `textual colors` in the README, the boost styling wasn't working a year ago either, so not a recent regression anyway!

**Comment by TomJGooding** [comment]
`$boost` according to the docs is "A color with alpha that can be used to create layers on a background", so I think the docs aren't an accurate representation showing this as pure black. This is rendered with Rich rather than Textual, so I expect that explains the difference.

https://github.com/Textualize/textual/blob/38e4cc08e4ee7d16a0faa16a456b1423d5f3a659/docs/guide/design.md?plain=1#L92-L101

**Comment by willmcgugan** [comment]
I suspect this is related to the color's alpha channel not being respected somewhere.

To whomever picks this up, please investigate, and figure out why these are different.

**Comment by rodrigogiraoserrao** [comment]
`$boost` is black but almost 100% transparent, so the way it looks will depend greatly on the background it's on.
The docs don't take into account the background (there's none) so it looks pitch black.
We've added a note in the docs to say that `$boost` will look different on different backgrounds.
