### ISSUE TITLE
Querying TabPane by ID returns multiple nodes

### ISSUE THREAD

**Issue by liancheng** [Textualize/textual#3695]
When assigning an ID to a `TabPane`, it seems that there is always a corresponding `ContentTab` created with the same ID, and therefore failing `query_one(id)` calls.

This [discussion thread](https://github.com/Textualize/textual/discussions/3666) is relevant, and I can use the `TabPane#foo` trick to workaround this issue. But this still seems to be a bug to me.

Repro:

```python
from textual.app import App, ComposeResult
from textual.widgets import TabbedContent, TabPane, Button


class ExampleApp(App):
    def compose(self) -> ComposeResult:
        with TabbedContent():
            yield TabPane("A", id="tab-a")

        yield Button("Repro")

    def on_button_pressed(self) -> None:
        for node in self.query("#tab-a"):
            self.log(f"### {node} ###")
        self.query_one("#tab-a")


if __name__ == "__main__":
    ExampleApp().run()
```

Clicking the button produces the following error:

```
TooManyMatches: Call to only_one resulted in more than one matched node
```

Relevant log lines in Textual console:

```
[01:05:37] INFO                                         tabbed_content_bug.py:14
### ContentTab(id='tab-a') ###
[01:05:37] INFO                                         tabbed_content_bug.py:14
### TabPane(id='tab-a') ###
```

# Textual Diagnostics

## Versions

| Name    | Value  |
|---------|--------|
| Textual | 0.41.0 |
| Rich    | 13.5.2 |

## Python

| Name           | Value                                               |
|----------------|-----------------------------------------------------|
| Version        | 3.11.2                                              |
| Implementation | CPython                                             |
| Compiler       | Clang 15.0.7                                        |
| Executable     | /Users/lian/local/src/textual/main/.venv/bin/python |

## Operating System

| Name    | Value                                                                                                 |
|---------|-------------------------------------------------------------------------------------------------------|
| System  | Darwin                                                                                                |
| Release | 22.6.0                                                                                                |
| Version | Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 |

## Terminal

| Name                 | Value           |
|----------------------|-----------------|
| Terminal Application | tmux (3.3a)     |
| TERM                 | screen-256color |
| COLORTERM            | truecolor       |
| FORCE_COLOR          | *Not set*       |
| NO_COLOR             | *Not set*       |

## Rich Console options

| Name           | Value               |
|----------------|---------------------|
| size           | width=80, height=23 |
| legacy_windows | False               |
| min_width      | 1                   |
| max_width      | 80                  |
| is_terminal    | False               |
| encoding       | utf-8               |
| max_height     | 23                  |
| justify        | None                |
| overflow       | None                |
| no_wrap        | False               |
| highlight      | None                |
| markup         | None                |
| height         | None                |

**Comment by rodrigogiraoserrao** [comment]
Hey @liancheng, thanks for the issue and for linking to the relevant discussion.

@willmcgugan, although this is “expected behaviour” in that we clearly implemented it this way, I think it makes no sense for us to cause this confusion to devs and to have queries break for no good reason.

As for a fix, something as simple as prefixing the internal IDs might cut it.

**Comment by davep** [comment]
Before calling something "internal" here, some consideration may want to be given to if the other use of the ID is desirable (styling of the tab, perhaps?). 

I'm not anywhere near the code at the moment, but thought it worth the caution. This could very well be a good example of working as intended but the widget needs proper "here's how it is composed, so this is what you need for styling" documentation. 

As a side issue: perhaps also figure out how to not have anyone feel full use of selectors is a "trick" when it's a core feature.

**Comment by davep** [comment]
Now that I am at a keyboard, just to illustrate what I mean, I'm not sure we'd want to intentionally make it harder do do this:

```python
from textual.app import App, ComposeResult
from textual.widgets import TabbedContent, TabPane, Label

class TabContentFun(App[None]):

    CSS = """
    ContentTab#first {
        color: red;
    }

    ContentTab#second {
        color: green;
    }
    """

    def compose(self) -> ComposeResult:
        with TabbedContent():
            with TabPane("First", id="first"):
                yield Label("First")
            with TabPane("Second", id="second"):
                yield Label("second")

if __name__ == "__main__":
    TabContentFun().run()
```

I sense that, for the most part, this issue is an offshoot of #3207.

**Comment by rodrigogiraoserrao** [comment]
This grants a more careful discussion, but the CSS shouldn't be a problem:

```tcss
TabPane#first > ContentTab {
    color: red;
}

TabPane#second > ContentTab {
    color: green;
}
```

**Comment by davep** [comment]
@rodrigogiraoserrao Do you mean with a rewrite of `TabbedContent` it shouldn't be a problem? Only, I don't see how that styling there would work right now given that `ContentTab` isn't within `TabPane`. The DOM of the example above is like this:

![Screenshot 2023-11-19 at 16 26 16](https://github.com/Textualize/textual/assets/28237/c34a01be-0f66-4d8f-8160-bba49e054d55)

**Comment by rodrigogiraoserrao** [comment]
😆 I messed up the structure in my head.

I guess [the issue 3207 you linked](https://github.com/Textualize/textual/issues/3207) is very relevant and we just need to decide what's more surprising:
That `.query_one("#first")` fails or that the ID of the content tab is actually something like `#_ct_first`.

If you're writing a CSS rule like `ContentTab#first` you already dug deep enough to realise that instances of `ContentTab` are being created for you, so you could probably figure out that their ID is built out _from_ the ID of the corresponding tab pane, but that it doesn't match.

However, if you create an explicit widget with a given ID, I think we should try to avoid creating other widgets with the same ID as much as possible, so that the internals of a compound widget produce the least amount of surprises.

**Comment by davep** [comment]
> That .query_one("#first") fails or that the ID of the content tab is actually something like #_ct_first

I'm not keen on the idea of the developer providing the their own ID, only to then have it modified by the code, adding a prefix or something, when the query language already has a great way to disambiguate things that, far from being a trick or workaround, is a feature of the framework. My primary reaction here is still that it's a documentation issue rather than anything else; `TabbedContent` and similar Textual-provided compound widgets should provide a handy map of their makeup in the docs.

Couple of other things that spring to mind (as additional things):

- Perhaps `TabbedContent` should have some sort of `get_tab_pane` method?
- Perhaps `TabbedContent` should have some sort of `get_tab` method too?

**Comment by willmcgugan** [comment]
The Tabs widget uses a `tab-X` scheme for naming. Either we make that unique somehow, or we just document it.

Its easy to workaround. I would use the naming convention `tabpane-X` for the `TabPane` objects. Or the query could be `TabPane#tab-foo`.

**Comment by rodrigogiraoserrao** [comment]
> I'm not keen on the idea of the developer providing the their own ID, only to then have it modified by the code.

The developer provided the ID for the `TabPane`, not for the `ContentTab`.
Obviously, if the user provides an ID for `TabPane`, we use it.
My suggestion was to generate a _unique_ ID for `ContentTab`, which the user has no way of specifying.

**Comment by davep** [comment]
> The developer provided the ID for the TabPane, not for the ContentTab.

Sure; mislead by documentation that could be more clear, is my initial reaction -- I'm not disputing the cause of the confusion that resulted in the original issue/discussion, or this re-issue. With better documentation in this regard they'd know they're providing the ID for the pane *and* the tab, and how to query them back, and all using the currently-available selector toolset.

> My suggestion was to generate a unique ID for ContentTab, which the user has no way of specifying.

How would I style the tabs themselves with this approach?

**Comment by rodrigogiraoserrao** [comment]
I also agree that the documentation should be improved.
I'm arguing that clearer documentation is _not_ enough.
I'm not willing to die on this hill, but I'm happy to argue in favour of my point of view.

 > How would I style the tabs themselves with this approach?

The `ContentTab`?
Provided that we document the mechanism through which the IDs for `ContentTab`s are generated, you can still use the ID.
For example, we can say “if you provide an ID for a `TabPane`, the compound widget `TabbedContent` will create a corresponding `ContentTab` widget that will have the same ID prefixed by `_contenttab-`. So, if your `TabPane` instance has the ID `bananas`, the corresponding `ContentTab` will have the ID `_contenttab-bananas`.


My argument is based on the premise that a good compound widget works well and is easy to use without the need for the user to dig into its internals.
If that premise stands, then `ContentTab`s should not be created with the exact same IDs as user-provided `TabPane`s because then the user will try to query their own `TabPane` and get extra `ContentTab` that the user didn't even know – and didn't _need_ to know – existed.

If someone wants to go into the docs to hyper-customise the `TabbedContent` – which is fine – then they'll read that the `TabbedContent` creates `ContentTab`s that are paired with `TabPane`s.
At that point, saying “content tabs and tab panes have the exact same IDs“ or “content tabs have their IDs generated from tab pane IDs” costs the users the same.

So, my conclusion is that for the lightweight user it is better to have different IDs and for the heavyweight user it's the same, from which it follows that `ContentTab` IDs should be generated from `TabPane` IDs with a well-defined and well-documented rule.

**Comment by davep** [comment]
My question about the styling was in reply to:

> My suggestion was to generate a unique ID for ContentTab, which the user has no way of specifying.

If the user has no way of specifying the ID, and it's always unique, how will they write CSS that targets it? It subsequently though seems you're envisaging a way that the user *can* specify it?

**Comment by rodrigogiraoserrao** [comment]
- “Unique” in opposition to “the same as the corresponding `TabPane`”.
 - “Which the user has no way of specifying” refers to the state of things _currently_. When we create a `TabbedContent`, the user has no control on how the `ContentTab` instances are created.

With these two 👆 clarifications, does my point make sense?

**Comment by willmcgugan** [comment]
I think the issue is that `ContentTab` gets an automatic `id`.  I'm not sure it even needs an `id`. Suggest we see if we can either remove it, or generate a unique `id` that won't clash.

**Comment by rodrigogiraoserrao** [comment]
> I think the issue is that `ContentTab` gets an automatic `id`. [...] Suggest we see if we can either remove it, or generate a unique `id` that won't clash.

I was trying to suggest we generate an ID that doesn't clash.
What did people interpret from my text?

>  I'm not sure it even needs an `id`.

Removing it doesn't break anything but prevents the user from styling different content tabs.
I think we need an ID that doesn't clash.

I suggest this:

```py
class ContentTab(Tab):
    """A Tab with an associated content id."""

    def __init__(self, label: Text, content_id: str, disabled: bool = False):
        # ...
        super().__init__(label, id=f"_contenttab-{content_id}", disabled=disabled)
```

**Comment by davep** [comment]
Mostly done. Probably an hour or so left to tidy up and tweak the docs.

**Comment by davep** [comment]
Decision reached: we'll add a `pane` property to `TabActivated`, add it to the properties that `@on` can select on, and remove `tab` from that list (but retain it as a properly the developer can access).
