### ISSUE TITLE
Investigate CI tests exceeding max execution time

### ISSUE THREAD

**Issue by TomJGooding** [Textualize/textual#3819]
I've noticed recently there have been a number of CI failures where "The job running on runner GitHub Actions 35 has exceeded the maximum execution time of 360 minutes."

It looks like it always fails on the same `test_notifications_loading_overlap_order` test and only on Windows 10 or 11. There's a long timeout on the toast notification in the test app, but I wouldn't have thought that would impact the snapshot testing?

Example run: https://github.com/Textualize/textual/actions/runs/7071771658

Might be worth investigating...?

**Comment by willmcgugan** [comment]
That is a strange one. It obviously does sometimes pass. The long timeout does jump out as a possible issue. Maybe the test code is waiting for the timer.

**Comment by willmcgugan** [comment]
I merged a change that dropped that notify timeout. Not sure yet if that fixed it, or it is still flakey.

Whoever picks this up: suggest you run the tests a few times on CI. To see if it reoccurs, before investigating further.

**Comment by TomJGooding** [comment]
It looks like that might have done the trick looking at the actions run today.

I'm still curious why it seems tests only sometimes might have been waiting on the timeout though!

**Comment by rodrigogiraoserrao** [comment]
Looking at all CI failures between the time or writing this and the time of [Will's comment about the pushed fix](https://github.com/Textualize/textual/issues/3819#issuecomment-1843352372) (~75 CI failures in total), I didn't see another instance of this issue with timeouts and `test_notifications_loading_overlap_order`.

The closest thing I found were workflow runs [#6322](https://github.com/Textualize/textual/actions/runs/7151804483) [#6323](https://github.com/Textualize/textual/actions/runs/7151844925) where _all_ runs (in the OS / Python version matrix) timed out at random points of the testing which is a clear anomaly but also likely due to some malfunction of GH Actions or a couple of test runs that didn't get cancelled properly.

No other CI failure investigated was due to timeouts.

For reference, in this time period I investigated there have also been ~125 CI runs that completed all tests successfully, so I conclude that the flakiness of this test has been solved.
