### ISSUE TITLE
Proposed modifications for the example of "Widgets"

### ISSUE THREAD

**Issue by jrycw** [Textualize/textual#3913]
This issue is intended to propose modifications to the example provided in [guide/widgets](https://textual.textualize.io/guide/widgets/#__tabbed_18_1), and the original code can be accessed [here](https://github.com/Textualize/textual/blob/ff70df87aad4d0c3ccad45709813299e04faeb03/docs/examples/guide/compound/byte03.py).

*  In reality, the `on_bit_switch_bit_changed` of `ByteEditor` receives `BitSwitch.BitChanged` but does not use it. Consequently, there is no need to pass the `bit` and `value` to `BitSwitch.BitChanged` while initializing.

* The `value`(`textual.reactive.reactive`) in `BitSwitch` appears to indicate the switch status (on/off). Therefore, it seems more natural to use `value = reactive(False)` instead of `value = reactive(0)`.

To summarize, I would suggest modifying `BitSwitch` with the following code:

```python
class BitSwitch(Widget):
    """A Switch with a numeric label above it."""

    DEFAULT_CSS = """
    BitSwitch {
        layout: vertical;
        width: auto;
        height: auto;
    }
    BitSwitch > Label {
        text-align: center;
        width: 100%;
    }
    """

    class BitChanged(Message):
        """Sent when the 'bit' changes."""

    value = reactive(False)

    def __init__(self, bit: int) -> None:
        self.bit = bit
        super().__init__()

    def compose(self) -> ComposeResult:
        yield Label(str(self.bit))
        yield Switch()

    def watch_value(self, value: bool) -> None:
        """When the value changes we want to set the switch accordingly."""
        self.query_one(Switch).value = value

    def on_switch_changed(self, event: Switch.Changed) -> None:
        """When the switch changes, notify the parent via a message."""
        event.stop()
        self.value = event.value
        self.post_message(self.BitChanged())
```

**Comment by rodrigogiraoserrao** [comment]
Hey @jrycw, thanks for opening this issue!

We represent `BitSwitch.value` with a switch because bits are commonly thought of in terms of on/off, like you said, but `BitSwitch.value` is the value of the binary expansion of the number in that bit, so it makes sense to keep it as an integer.
I'll go through the example to make sure it's clear when we're working with integers vs Booleans.

As for the event accepting the `bit` and `value` parameters, I believe the author of that guide added them because those are sensible things to include in that sort of message...
But it may be confusing for people reading the code because they can't see those parameters being used...
Point taken.

**Comment by rodrigogiraoserrao** [comment]
Apparently [the remainder of the code](https://github.com/Textualize/textual/blob/ff70df87aad4d0c3ccad45709813299e04faeb03/docs/examples/guide/compound/byte03.py#L120) also thinks `BitSwitch.value` is a Boolean, so I'll go with your suggestion!

**Comment by rodrigogiraoserrao** [comment]
See [the PR linked above](https://github.com/Textualize/textual/pull/3917) for the resolution of this issue.
