### ISSUE TITLE
TabbedContent active attribute doesn't post message TabActivated + doesn't arrange tabs

### ISSUE THREAD

**Issue by charles-001** [Textualize/textual#4150]
Hello,

I noticed that when using `active` reactive attribute, there is no message posted to `TabActivated`. I also noticed that if the tab bar is larger than the terminal, it doesn't correctly adjust the tabs to show what's around them as if you clicked on it.

Please see the MRE below to understand the issue:
```python
from textual import on
from textual.app import App
from textual.widgets import Button, TabbedContent, TabPane


class TabApp(App):
    def compose(self):
        with TabbedContent(id="tabbed_content"):
            for tab_id in range(50):
                yield TabPane(f"Tab_{tab_id}", id=f"tab_{tab_id}")

        yield Button("First Tab", id="first_tab")
        yield Button("Last Tab", id="last_tab")

    @on(TabbedContent.TabActivated, "#tabbed_content")
    def tab_changed(self, event: TabbedContent.TabActivated):
        self.notify(f"Tab changed {event.tab.id}")

    @on(Button.Pressed, "#first_tab")
    def on_first_tab(self):
        self.query_one("#tabbed_content", TabbedContent).active = "tab_0"

    @on(Button.Pressed, "#last_tab")
    def on_last_tab(self):
        self.query_one("#tabbed_content", TabbedContent).active = "tab_49"


app = TabApp()
app.run()
```

Thanks!

**Comment by TomJGooding** [comment]
Related issue:

- #3869

I'm not suggesting this should be marked as duplicate, rather just trying to link this to the overarching issue.

**Comment by davep** [comment]
Using the following code we can see that the "scroll tab into view" problem stems from `Tabs`:

```python
from textual import on
from textual.app import App, ComposeResult
from textual.containers import Vertical
from textual.widgets import TabbedContent, TabPane, Tabs, Tab, Label, Log, Rule

class TabbedContentActiveApp(App[None]):

    BINDINGS = [
        ("c", "jump_tabbed_content"),
        ("t", "jump_tabs")
    ]

    def compose(self) -> ComposeResult:
        with Vertical() as container:
            container.border_title = "TabbedContent version"
            with TabbedContent():
                for n in range(200):
                    with TabPane(f"Filler {n}", id=f"filler-{n}"):
                        yield Label(f"Filler tab {n}")
                with TabPane("PICK ME!", id="pick-me"):
                    yield Label("This is the tab we're after")
        with Vertical() as container:
            container.border_title = "Tabs version"
            yield Tabs(
                *(
                    tuple(Tab(f"Filler {n}", id=f"filler-{n}") for n in range(200)) +
                    (Tab("PICK ME!", id="pick-me"),)
                )
            )
        yield Rule()
        yield Log()

    @on(TabbedContent.TabActivated)
    @on(Tabs.TabActivated)
    def log_messages(self, event: TabbedContent.TabActivated | Tabs.TabActivated) -> None:
        self.query_one(Log).write_line(f"{event!r}")

    def action_jump_tabbed_content(self) -> None:
        self.query_one(TabbedContent).active = "pick-me"

    def action_jump_tabs(self) -> None:
        self.query_one("Vertical > Tabs", Tabs).active = "pick-me"

if __name__ == "__main__":
    TabbedContentActiveApp().run()
```

We can also see that `Tabs` *does* post the relevant message when `active` is set, so most likely `TabbedContent` isn't handling that situation correctly.

**Comment by davep** [comment]
While the "screen into view when activated" thing was a nice and easy one-liner; the `TabbedContent.TabActivated` issue is a bit tricker at first glance. It's [*very* deliberately not done](https://github.com/Textualize/textual/blob/fa4f75fd25c625d150e11c476bf468bf506c3400/src/textual/widgets/_tabbed_content.py#L549) in the code, most likely because of the Catch-22 of a change to `TabbedContent.active` causing a change to `Tabs.active` which *does* post a `Tabs.Activated`, which in turn triggers [`TabbedContent._on_tabs_tab_activated`](https://github.com/Textualize/textual/blob/fa4f75fd25c625d150e11c476bf468bf506c3400/src/textual/widgets/_tabbed_content.py#L509-L522), which in turn [assigns `TabbedContent.active`](https://github.com/Textualize/textual/blob/fa4f75fd25c625d150e11c476bf468bf506c3400/src/textual/widgets/_tabbed_content.py#L516), which would fore the `TabbedContent.active` watcher, which would...

Unless I'm missing the obvious (highly likely) this might take a bit more than one line to work around.

**Comment by charles-001** [comment]
@davep - that makes sense. My main issue was actually the active tab not coming into view which you've fixed :) Thank you!
