### ISSUE TITLE
Support document with multiple newline styles

### ISSUE THREAD

**Issue by davidbrochart** [Textualize/textual#4207]
The [_detect_newline_style(text)](https://github.com/Textualize/textual/blob/65c4cce2156e062a199f3ef250c403013168c8d0/src/textual/document/_document.py#L48) method doesn't support a document mixing different newline styles, for instance `\r` and `\n`. I'm not sure if this is supposed to happen, but I ended up with such a document, probably while copy/pasting.
Would it make sense to support multiple newline styles, or should the document detect that and unify the styles after loading the text?

**Comment by darrenburns** [comment]
Right now, it detects the first newline type and then when you export the text it will unify them all to be of the same type. We opted not to support mixed line endings

**Comment by darrenburns** [comment]
If you've somehow got a document with mixed line endings when you retrieve the value of `text_area.text`, that's a bug and we should look at it.

If you want to change the line ending of the document, you could do `text_area.document._newline = "\n"` for example (we could look to make `_newline` public).

The current expected behaviour is: when you pass text into replace range, the line endings are converted to the line ending for the current document.

**Comment by davidbrochart** [comment]
> The current expected behaviour is: when you pass text into replace range, the line endings are converted to the line ending for the current document.

Thanks, then I must have done something wrong on my side.
