### ISSUE TITLE
Integer validator does not work as expected permitting floating point numbers

### ISSUE THREAD

**Issue by arcivanov** [Textualize/textual#4718]
The culprit lies in this piece of code:

```python
        # We know it's a number, but is that number an integer?
        is_integer = float(value).is_integer()
        if not is_integer:
            return ValidationResult.failure([Integer.NotAnInteger(self, value)])
```

The problem is that `float("1.").is_integer()` and `float("1.0").is_integer()` are all `True` (thankfully `float("1.1").is_integer()` is not).

This issue is not purely cosmetic either. `int("1.")` or `int("1.0")`  all raise exceptions:

```
>>> int("1.0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '1.0'
>>> int("1.")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '1.'
```

Therefore a validator will validate a string as an integer that cannot be parsed as an integer by the `int` type.

**Comment by merriam** [comment]
Hmm.... Funky.

This is an error, meaning the code should be wrong.   On the other hand, there is no way to cause the error to express, because `_input.py` restricts the dot.   That is, you cannot type the '.' because the `_RESTRICT_TYPES` regular expression for integers is just `r"[-+]?\d*"`.    This means "000032" is fine, but "1_000_000" is not.   In practice, there is no sequence of +/- followed by digits in Python that is not an integer.

There is also this error code as well for in the float validator,`if float_value in {math.nan, math.inf, -math.inf}...`which will not trigger for a NaN, as `float('NaN') != float('NaN')`.  It too is an error, but not expressible because of regex.
 
Let me cogitate on input validation for a minute, and, baring insight, I'll put in a PR next week.
