### ISSUE TITLE
Screen.dismiss doesn't call the callback function if it's called with no args

### ISSUE THREAD

**Issue by darrenburns** [Textualize/textual#4790]
e.g. `screen.dismiss()`

or in a Binding `Binding(..., action="screen.dismiss", ...)`.

Confirmed with this MRE:

```python
from textual.app import App, ComposeResult
from textual.screen import Screen
from textual.widgets import Static


class MyScreen(Screen):
    BINDINGS = [("space", "screen.dismiss()", "Dismiss")]

    def compose(self) -> ComposeResult:
        yield Static("Hello")


class MyApp(App):
    def on_mount(self) -> None:
        def callback(sd):
            self.notify("Callback")

        self.push_screen(MyScreen(), callback)

    def compose(self) -> ComposeResult:
        yield Static("Default Screen")


if __name__ == "__main__":
    app = MyApp()
    app.run()
```

**Comment by willmcgugan** [comment]
This does seem like it was by design.

From the dismiss docstring:

>        If `result` is provided and a callback was set when the screen was [pushed][textual.app.App.push_screen], then
>       the callback will be invoked with `result`.

I think the rationale might have been that the callback exists to receive the argument to `dismiss()`. And if you don't supply one, then you don't need the callback.

On reflection supplying a callback and then discarding it feels like a wart.
