### ISSUE TITLE
Tree with many nodes + Input + TabbedContent can lead to some nodes not being displayed

### ISSUE THREAD

**Issue by armijnhemel** [Textualize/textual#4805]
I am currently bumping into an issue where not all the nodes of a Tree are displayed. My program has an Input field at the top, then TabbedContent, with two TabPanes each containing a Tree. When I add 100 nodes to the trees only the first 98 are displayed. When I remove the TabbedContent, or the Input, then all nodes are displayed. I have absolutely no idea what I am doing wrong here.

I have tested this on Textual 0.70, 0.72 and 0.74. A simple test application is attached, as well as three screenshots.

[example_bug_tree_tabbed_input.zip](https://github.com/user-attachments/files/16381454/example_bug_tree_tabbed_input.zip)

![Screenshot at 2024-07-25 19-08-09](https://github.com/user-attachments/assets/89aa32dc-0801-4378-8048-12f202090a52)
![Screenshot at 2024-07-25 19-07-45](https://github.com/user-attachments/assets/805bfc58-c09e-4805-bbff-df3b3ade9ffc)
![Screenshot at 2024-07-25 19-07-27](https://github.com/user-attachments/assets/606f9d1f-b45c-4377-b563-28e569746d98)

**Comment by TomJGooding** [comment]
This simple method usually helps me debug layout issues:

```
TabbedContent {
  border: solid red;
}
```

This shows that the `TabbedContent` is overflowing its container. The [default CSS for this widget has `height: auto`](https://github.com/Textualize/textual/blob/262b3af00fe36e3c7cb34a72e9a333d1eee2f885/src/textual/widgets/_tabbed_content.py#L242), so try changing this to 1fr in your CSS, or add a `max-height`.

**Comment by armijnhemel** [comment]
Thank you! This definitely works. I am not sure if this is an actual bug I will leave closing the issue to you.

**Comment by TomJGooding** [comment]
Maybe `TabbedContent` _could_ have a `max-height` by default? I do remember other issues/discussions where people have been caught out by this, but I'm conscious any change to the default CSS might break other layouts!

Just to clarify, the problem is where your `TabbedContent` is inside a `Container`. The `Container` has a default height of 1fr (and doesn't scroll). so it does make sense why your `TabbedContent` overflowed according to the current CSS.

I'll leave the decision to the Textual maintainers.
