### ISSUE TITLE
Nested comments in CSS

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#503]
Pretty sure nested comments don't work as expected in Textual CSS.

i.e. this breaks on parsing:

```
/*
#foo {
    /*
    text-style: bold
*/
}
*/
```

Nested comments should work.

**Comment by DrBenton** [comment]
Out of curiosity I just checked - as often ^_^ - the equivalent behaviour in the browser, and it turns out that "browsers' CSS" don't support nested comments in CSS.

Maybe we could simply imitate them? :slightly_smiling_face: 
People using advanced text editors such has VS Code would instantly see that something is wrong if they use nested comments in a CSS file anyhow, as the editor clearly flags it as a syntax error. 
So making it work when the text editor says it's wrong might not be the most intuitive behaviour to follow for Textual? What do you folks think? @willmcgugan @darrenburns 

### Some screenshots to illustrate this :camera_flash: 

##### Web browser behaviour

In a web browser the result of that:
![Screenshot from 2022-05-19 14-11-27](https://user-images.githubusercontent.com/722388/169301531-42c1d435-e57d-480b-a6ca-4b1284016efa.png)
...is this:
![Screenshot from 2022-05-19 14-12-41](https://user-images.githubusercontent.com/722388/169301642-6367e50c-b0be-4165-bd45-5e5efd9ac433.png)

##### Syntactic helpers behaviour

Using nested comments in CSS in an editor such as VS Code is clearly flagged as an error:
![Screenshot from 2022-05-19 14-17-38](https://user-images.githubusercontent.com/722388/169302720-e87ac258-9e17-463c-97ca-7e774d8064be.png)

Doesn't look good in Pygments either:
![Screenshot from 2022-05-19 14-20-45](https://user-images.githubusercontent.com/722388/169303245-33552f15-5971-4b28-981b-9c7778ea428c.png)

**Comment by willmcgugan** [comment]
I assumed that would have worked like C++!

Fair enough. If the browser doesn't support it, neither should we.

**Comment by DrBenton** [comment]
> I assumed that would have worked like C++!

To be honest I thought it would be working in web browsers too!
I've been writing CSS since 1998, and that's the first time I realise that it's not the case :sweat_smile: 

"Every day is a school day" :man_student:
