### ISSUE TITLE
Using `dismiss` in `call_after_refresh` now raises an error.

### ISSUE THREAD

**Issue by JoeZiminski** [Textualize/textual#5049]
I just wanted to highlight change in behaviour that I could not see documented in the change log. Previously I was calling `call_after_refresh(lambda: self.dismiss(True))` within a `ModalScreen`. Now, this gives an error:

`ScreenError: Can't await screen.dismiss() from the screen's message handler; try removing the await`

I think because of a new check where this error is raised. I found another workaround to acheive what I wanted, but thought I'd raise this in case 1) this change in behaviour was not intended 2) an improved error mesage could be given. It took me a while to track it down, if suitable,  if the error could indicate not to use `self.dismiss` in `call_after_refresh` it might be useful. 

Sorry I cannot give clear versions on which this works / does not work. But it is OK in `0.71.0` but not in most recent version.

**Comment by TomJGooding** [comment]
I'm not sure what may have changed, but why use a lambda rather than `call_after_refresh(self.dismiss, True)`?

**Comment by willmcgugan** [comment]
call_after_refresh will execute the callback within the screen's message pump. If it returns something awaitable (which `dismiss` does) then it will await it.

The error is because it would end up waiting for itself to complete. i.e. a deadlock.

it is an edge case. Can't think of any way to auto-detect that right now.

However, I suspect it isn't necessary. From a quick look at your project I gather you want a refresh before the UI freezes. You almost certainly want to use [workers](https://textual.textualize.io/guide/workers/) to prevent freezing.

I suspect that if you were to add `@work` to your button handler, that would prevent freezing and negate the need for call_after_refresh.

**Comment by JoeZiminski** [comment]
Thanks a lot @TomJGooding @willmcgugan, thanks both! That all makes sense, thanks for the tip on using works, looking forward to trying that out! I guess this will also allow the use of [data loader](https://textual.textualize.io/widgets/loading_indicator/#__tabbed_1_1) widget which I was very keen on.  Cheers!
