### ISSUE TITLE
Implement cursor

### ISSUE THREAD

**Issue by leftbones** [Textualize/textual#510]
I've been reading the source code (since there's not much documentation) and haven't found any ways to move the cursor around, or even really show the cursor.

For learning Textual, I've been making a modified version of the code viewer example. For starters I'm trying to implement cursor movement with HJKL, for scrolling through the code viewer, and eventually for when I attempt to turn this into an editor rather than just a viewer.

**Comment by adamlwgriffiths** [comment]
https://github.com/sirfuzzalot/textual-inputs has an example of an input with a cursor.
But it uses an actual character to represent it, rather than a native cursor as you would in ncurses.
It has the effect of causing text to the right of the cursor to jump a character left or right as you move the cursor about.
It's.... really not good, but it's the only example I've seen so far.

A proper cursor would be **much** preferred.

**Comment by willmcgugan** [comment]
https://github.com/Textualize/textual/wiki/Sorry-we-closed-your-issue
