### ISSUE TITLE
Review README

### ISSUE THREAD

**Issue by willmcgugan** [Textualize/textual#891]
Review the README in the css branch for typos / grammar.

Suggest improvements. Is there anything that should be README as well as / in preference to the docs?

Perhaps a getting started section?

**Comment by davep** [comment]
Main TODO right now would seem to be to add a link to the main Textual documentation, especially to the tutorial. Rather than a "getting started" section I think that pointer makes more sense.

Also TODO: a go with a snappy animated application that is as few lines of code as possible, so people can quickly see what can be built and what the code looks like.

Point being: keep the README fairly compact and save the getting started, etc, for the main docs.
